# Form implementation generated from reading ui file 'torf_gui/mediainfolocation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MediainfoLocationDialog:
    def setupUi(self, MediainfoLocationDialog):
        MediainfoLocationDialog.setObjectName("MediainfoLocationDialog")
        MediainfoLocationDialog.setWindowModality(QtCore.Qt.WindowModal)
        MediainfoLocationDialog.resize(605, 253)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MediainfoLocationDialog.sizePolicy().hasHeightForWidth()
        )
        MediainfoLocationDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(MediainfoLocationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.programNameLabel = QtWidgets.QLabel(MediainfoLocationDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.programNameLabel.sizePolicy().hasHeightForWidth()
        )
        self.programNameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.programNameLabel.setFont(font)
        self.programNameLabel.setObjectName("programNameLabel")
        self.verticalLayout.addWidget(self.programNameLabel)
        self.label = QtWidgets.QLabel(MediainfoLocationDialog)
        self.label.setMaximumSize(QtCore.QSize(587, 20))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.mediainfoLocationEdit = QtWidgets.QLineEdit(
            MediainfoLocationDialog
        )
        self.mediainfoLocationEdit.setEnabled(True)
        self.mediainfoLocationEdit.setObjectName("mediainfoLocationEdit")
        self.verticalLayout.addWidget(self.mediainfoLocationEdit)
        self.browseButton = QtWidgets.QPushButton(MediainfoLocationDialog)
        self.browseButton.setObjectName("browseButton")
        self.verticalLayout.addWidget(self.browseButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(MediainfoLocationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(MediainfoLocationDialog)
        self.buttonBox.accepted.connect(MediainfoLocationDialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(MediainfoLocationDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MediainfoLocationDialog)

    def retranslateUi(self, MediainfoLocationDialog):
        _translate = QtCore.QCoreApplication.translate
        MediainfoLocationDialog.setWindowTitle(
            _translate("MediainfoLocationDialog", "MediaInfo")
        )
        self.programNameLabel.setText(
            _translate("MediainfoLocationDialog", "MediaInfo")
        )
        self.label.setText(
            _translate("MediainfoLocationDialog", "Path to MediaInfo")
        )
        self.browseButton.setText(
            _translate("MediainfoLocationDialog", "Browse...")
        )
